#ifndef QCGAUGEWIDGET_GLOBAL_H
#define QCGAUGEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCGAUGEWIDGET_LIBRARY)
#  define QCGAUGEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QCGAUGEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QCGAUGEWIDGET_GLOBAL_H
